// FILE AUTOGENERATED BY t18s
// You can safely add this to your .gitignore

/** TypeSafe translations for your Svelte app. */
declare module "$t18s" {
    import type { Writable, Readable } from 'svelte/store';

    /** The available locales */
    type Locales = ["ru","en"];
    
    /** The known locales */
    export type Locale = Locales[number];
    
    /** The fallback locale that's currently in use. */
    export const fallbackLocale: "en";
    
    /** The available locales */
    export const locales : Locales;
    
    /** The current locale */
    export const locale: Writable<Locale>;
    
    /**
     * Set the current locale. Equivalent to `locale.set(newLocale)`
     * @param newLocale The new locale
     */
    export function setLocale(newLocale: Locale): void;
    
    /** Convenience function to check if something is a valid locale. */
    export const isLocale: (maybeLocale: unknown) => maybeLocale is Locale;
}

/** The messages for the domain . Add messages by adding a file at /home/thekeeper/nocow/dev/receiptmaker/src/translations with the name .[locale].yaml */
declare module "$t18s/messages" {
    export const receipts: (values?: undefined) => string;
    export const store: (values?: undefined) => string;
    export const settings: (values?: undefined) => string;
    export const test: (values?: undefined) => string
}